# Generated by Django 4.1.7 on 2023-03-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Square Name')),
                ('x', models.CharField(max_length=120, verbose_name='X')),
                ('y', models.CharField(max_length=120, verbose_name='Y')),
                ('z', models.CharField(max_length=120, verbose_name='Z')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Square Name')),
                ('x', models.CharField(max_length=120, verbose_name='X')),
                ('y', models.CharField(max_length=120, verbose_name='Y')),
                ('z', models.CharField(max_length=120, verbose_name='Z')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('adress', models.CharField(max_length=120, verbose_name='Adress')),
                ('zip_code', models.CharField(max_length=120, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=120, verbose_name='Contact Phone')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Square Name')),
                ('x', models.CharField(max_length=120, verbose_name='X')),
                ('y', models.CharField(max_length=120, verbose_name='Y')),
                ('z', models.CharField(max_length=120, verbose_name='Z')),
                ('description', models.TextField(blank=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.environment')),
                ('occupants', models.ManyToManyField(blank=True, to='event.myplayer')),
            ],
        ),
        migrations.CreateModel(
            name='MyClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('y', models.CharField(max_length=120, verbose_name='Y')),
                ('z', models.CharField(max_length=120, verbose_name='Z')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('avenue', models.CharField(max_length=120, verbose_name='Avenue')),
                ('manager', models.CharField(max_length=120, verbose_name='Manager')),
                ('description', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, to='event.myclubuser')),
            ],
        ),
    ]
