# Generated by Django 4.1.7 on 2023-03-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='x',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='y',
        ),
    ]
