# Generated by Django 4.1.7 on 2023-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_userprofile_name_remove_userprofile_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='x',
            field=models.IntegerField(default=0, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='y',
            field=models.IntegerField(default=0, verbose_name='y'),
        ),
    ]
