# Generated by Django 4.1.7 on 2023-03-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_userprofile_x_userprofile_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xpos',
            field=models.IntegerField(default=0, verbose_name='xpos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ypos',
            field=models.IntegerField(default=0, verbose_name='ypos'),
        ),
    ]
