# Generated by Django 4.1.7 on 2023-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='occupants2',
        ),
        migrations.AddField(
            model_name='square',
            name='occupants3',
            field=models.ManyToManyField(blank=True, default=[], to='event.userprofile'),
        ),
    ]
