# Generated by Django 4.1.7 on 2023-03-29 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0010_remove_square_occupants2_square_occupants3'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=120, verbose_name='User Name')),
                ('x', models.IntegerField(default=0, verbose_name='x')),
                ('y', models.IntegerField(default=0, verbose_name='y')),
                ('xpos', models.IntegerField(default=0, verbose_name='xpos')),
                ('ypos', models.IntegerField(default=0, verbose_name='ypos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
