# Generated by Django 4.1.7 on 2023-04-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_square_occupants4'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mode',
            field=models.CharField(blank=True, max_length=30, verbose_name='mode'),
        ),
    ]
