# Generated by Django 4.1.7 on 2023-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_userprofile_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='original_image',
            field=models.CharField(default='null.png', max_length=100),
        ),
        migrations.AddField(
            model_name='square',
            name='territory',
            field=models.TextField(blank=True),
        ),
    ]
