# Generated by Django 4.1.7 on 2023-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_square_original_image_square_territory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(default='question_name', max_length=120, verbose_name='Question_name')),
                ('question_swedish', models.CharField(default='swedish_question', max_length=1000, verbose_name='question_swedish')),
                ('answer1_swedish', models.CharField(default='swedish_answer1', max_length=1000, verbose_name='answer1_swedish')),
                ('answer2_swedish', models.CharField(default='swedish_answer2', max_length=1000, verbose_name='answer2_swedish')),
                ('answer3_swedish', models.CharField(default='swedish_answer3', max_length=1000, verbose_name='answer3_swedish')),
                ('answer4_swedish', models.CharField(default='swedish_answer4', max_length=1000, verbose_name='answer4_swedish')),
                ('question_english', models.CharField(default='english_question', max_length=1000, verbose_name='question_english')),
                ('answer1_english', models.CharField(default='english_answer1', max_length=1000, verbose_name='answer1_english')),
                ('answer2_english', models.CharField(default='english_answer2', max_length=1000, verbose_name='answer2_english')),
                ('answer3_english', models.CharField(default='english_answer3', max_length=1000, verbose_name='answer3_english')),
                ('answer4_english', models.CharField(default='english_answer4', max_length=1000, verbose_name='answer4_english')),
                ('correct_answer', models.IntegerField(default=0, max_length=10, verbose_name='correct_answer')),
                ('difficulty', models.FloatField(default='0.0', max_length=20, verbose_name='difficulty')),
                ('area1', models.CharField(default='general', max_length=1000, verbose_name='area1')),
                ('area2', models.CharField(default='area2', max_length=1000, verbose_name='area2')),
                ('area3', models.CharField(default='area3', max_length=1000, verbose_name='area3')),
            ],
        ),
    ]
