# Generated by Django 4.1.7 on 2023-04-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_rename_question_name_question_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.question'),
        ),
    ]
