# Generated by Django 4.1.7 on 2023-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_userprofile_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_xpos',
            field=models.IntegerField(default=0, verbose_name='pending_xpos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_ypos',
            field=models.IntegerField(default=0, verbose_name='pending_ypos'),
        ),
    ]
