# Generated by Django 4.1.7 on 2023-04-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_userprofile_pending_xpos_userprofile_pending_ypos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='correct_answers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wrong_answers',
            field=models.IntegerField(default=0, verbose_name='wrong_answers'),
        ),
    ]
