# Generated by Django 4.1.7 on 2023-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_userprofile_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='regular', max_length=120, verbose_name='user_type'),
        ),
    ]
