# Generated by Django 4.1.7 on 2023-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
