# Generated by Django 4.1.7 on 2023-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_userprofile_last_active_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='map_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='map_label'),
        ),
    ]
