# Generated by Django 4.1.7 on 2023-04-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_square_map_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_label_holder',
            field=models.CharField(default='x', max_length=120, verbose_name='temp_label_holder'),
        ),
    ]
