# Generated by Django 4.1.7 on 2023-04-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_userprofile_temp_label_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='question_area1',
            field=models.CharField(blank=True, max_length=120, verbose_name='map_label'),
        ),
    ]
