# Generated by Django 4.1.7 on 2023-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_square_question_area1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_question_holder',
            field=models.CharField(default='x', max_length=120, verbose_name='temp_question_holder'),
        ),
    ]
