# Generated by Django 4.1.7 on 2023-04-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_userprofile_temp_question_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='question_area1',
            field=models.CharField(blank=True, max_length=120, verbose_name='question1'),
        ),
    ]
