# Generated by Django 4.1.7 on 2023-04-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_userprofile_question_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Square Name')),
                ('x', models.CharField(max_length=120, verbose_name='X')),
                ('y', models.CharField(max_length=120, verbose_name='Y')),
                ('z', models.CharField(max_length=120, verbose_name='Z')),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(default='null.png', max_length=100)),
                ('territory', models.TextField(blank=True)),
                ('map_label', models.CharField(blank=True, max_length=120, verbose_name='map_label')),
                ('question_area1', models.CharField(blank=True, max_length=120, verbose_name='questionarea1')),
                ('question_area2', models.CharField(blank=True, max_length=120, verbose_name='questionarea2')),
                ('question_area3', models.CharField(blank=True, max_length=120, verbose_name='questionarea3')),
                ('question_area4', models.CharField(blank=True, max_length=120, verbose_name='questionarea4')),
                ('occupants', models.ManyToManyField(blank=True, to='event.myplayer')),
            ],
        ),
    ]
