# Generated by Django 4.1.7 on 2023-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_beacon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='occupants',
        ),
        migrations.AddField(
            model_name='beacon',
            name='question_area1_strength',
            field=models.CharField(blank=True, max_length=120, verbose_name='questionarea1_strength'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='x',
            field=models.IntegerField(max_length=120, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='y',
            field=models.IntegerField(max_length=120, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='z',
            field=models.IntegerField(max_length=120, verbose_name='Z'),
        ),
    ]
