# Generated by Django 4.1.7 on 2023-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_remove_beacon_occupants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='x',
            field=models.IntegerField(default=0, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='z',
            field=models.IntegerField(default=0, verbose_name='Z'),
        ),
    ]
