# Generated by Django 4.1.7 on 2023-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_alter_beacon_question_area1_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_question_area_holder',
            field=models.CharField(default='x', max_length=120, verbose_name='temp_question_area_holder'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_question_area_strength_holder',
            field=models.CharField(default='0', max_length=120, verbose_name='temp_question_area_strength_holder'),
        ),
    ]
