# Generated by Django 4.2 on 2023-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_beacon_buffer_alter_beacon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer1_english',
            field=models.CharField(default='english_answer1', max_length=300, verbose_name='answer1_english'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1_swedish',
            field=models.CharField(default='swedish_answer1', max_length=300, verbose_name='answer1_swedish'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2_english',
            field=models.CharField(default='english_answer2', max_length=300, verbose_name='answer2_english'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2_swedish',
            field=models.CharField(default='swedish_answer2', max_length=300, verbose_name='answer2_swedish'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3_english',
            field=models.CharField(default='english_answer3', max_length=300, verbose_name='answer3_english'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3_swedish',
            field=models.CharField(default='swedish_answer3', max_length=300, verbose_name='answer3_swedish'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4_english',
            field=models.CharField(default='english_answer4', max_length=300, verbose_name='answer4_english'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4_swedish',
            field=models.CharField(default='swedish_answer4', max_length=300, verbose_name='answer4_swedish'),
        ),
        migrations.AlterField(
            model_name='question',
            name='area1',
            field=models.CharField(default='general', max_length=300, verbose_name='area1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='area2',
            field=models.CharField(default='area2', max_length=300, verbose_name='area2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='area3',
            field=models.CharField(default='area5', max_length=300, verbose_name='area5'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_english',
            field=models.CharField(default='english_question', max_length=300, verbose_name='question_english'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_swedish',
            field=models.CharField(default='swedish_question', max_length=300, verbose_name='question_swedish'),
        ),
    ]
