# Generated by Django 4.2.4 on 2023-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_genome_dir',
            field=models.CharField(default='', max_length=120, verbose_name='user_current_genome_dir'),
        ),
    ]
