# Generated by Django 4.2.4 on 2023-10-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_userprofile_current_genome_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('y', models.CharField(max_length=120, verbose_name='Y')),
                ('z', models.CharField(max_length=120, verbose_name='Z')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.environment')),
            ],
        ),
        migrations.CreateModel(
            name='genomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('path', models.CharField(max_length=120, verbose_name='path')),
                ('extra', models.CharField(max_length=120, verbose_name='extra')),
                ('is_dir', models.CharField(max_length=120, verbose_name='Manager')),
                ('description', models.TextField(blank=True)),
                ('contigs_num', models.IntegerField(default=0, verbose_name='contigs_num')),
                ('files_num', models.IntegerField(default=0, verbose_name='contigs_num')),
                ('dir_files', models.ManyToManyField(blank=True, to='event.myfile')),
            ],
        ),
    ]
