# Generated by Django 4.2.4 on 2023-10-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_myfile_genomeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomeentry',
            name='contigs_num',
            field=models.IntegerField(default=-1, verbose_name='contigs_num'),
        ),
        migrations.AlterField(
            model_name='genomeentry',
            name='files_num',
            field=models.IntegerField(default=-1, verbose_name='contigs_num'),
        ),
        migrations.AlterField(
            model_name='genomeentry',
            name='is_dir',
            field=models.CharField(default=-1, max_length=120, verbose_name='is_dir'),
        ),
    ]
