# Generated by Django 4.2.4 on 2023-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_genomeentry_contigs_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='genome_size',
            field=models.IntegerField(default=-1, verbose_name='genome_size'),
        ),
    ]
