# Generated by Django 4.2.4 on 2023-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_genomeentry_blast_files_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='work_files_dir',
            field=models.CharField(default='D:/workfiles/', max_length=120, verbose_name='work_files_dir'),
        ),
    ]
