# Generated by Django 4.2.4 on 2023-10-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_genomeentry_work_files_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='concat_fasta_file',
            field=models.CharField(default='', max_length=120, verbose_name='work_files_dir'),
        ),
        migrations.AlterField(
            model_name='genomeentry',
            name='path',
            field=models.CharField(default='-1', max_length=120, verbose_name='path'),
        ),
    ]
